# Use zsh
set-option -g default-shell /bin/zsh

# Split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind '%'
unbind 'C-w'

# Mouse mode
set -g mouse on

# Don't rename windows
set-option -g allow-rename off

# Command to change default directory  
bind -n M-c new-window -c '#{pane_current_path}'
bind -n M-| split-window -h -c '#{pane_current_path}'
bind -n M-- split-window -v -c '#{pane_current_path}'

