# Default shell
shell tmux

# Fonts
font_family ComicShannsMono Nerd Font Mono
italic_font JetBrainsMono Nerd Font Mono
bold_italic_font JetBrainsMono Nerd Font Mono

# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME
