# Default shell
shell tmux

# Fonts
font_family ComicShannsMono Nerd Font
italic_font JetBrainsMono Nerd Font Mono
bold_italic_font JetBrainsMono Nerd Font Mono

# Window 
initial_window_width 1280
initial_window_height 720
hide_window_decorations yes
confirm_os_window_close 0

# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME
