format = '(Duration: $cmd_duration)$line_break$shell $directory$sudo$git_status$git_metrics$fill$git_branch$python$rust$azure $line_break '
add_newline = false

[character]
format = " "

[azure]
disabled = false
format = "$symbol[($username)  [  ](bright-purple)($subscription)]($style) "
symbol = "[](bright-purple)  "
style = "white"

[shell]
disabled = false
bash_indicator = ''
zsh_indicator = '󰵁'
powershell_indicator = ""
nu_indicator = "𝝢"
format = '[$indicator]($style) '
style = 'bright-purple'

[cmd_duration]
min_time = 5000
format = '[$duration]($style)'
style = 'white'

[directory]
home_symbol = '󱂵 '
style = 'white'

[fill]
symbol = ' '
style = 'white'

[username]
format = ' [$user]($style)'
show_always = true
style_user = 'bright-purple'

[hostname]
format = '[$ssh_symbol$hostname]($style)'
ssh_only = false
style = 'bright-purple'

[localip]
ssh_only = false
disabled = false
style = 'white'

[container]
symbol = "  "
format = '[$symbol]($style)'
style = 'bright-purple'

[git_status]
format = ' ([\[$all_status$ahead_behind\]]($style) )'

[python]
symbol = "[](bright-purple)  "
format = " ${symbol}[(${version})($virtualenv)  ]($style)"
version_format = "${raw}"
detect_extensions = ['py', 'ipynb']
style = 'white'

[sudo]
disabled = false
format = "[$symbol](style)"
symbol = '🤓'
style = 'bright-purple'

[git_metrics]
disabled = false

[git_branch]
symbol = "[](bright-purple)  "
format = "$symbol[$branch]($style) "
style = "white"

[memory_usage]
disabled = false
threshold = -1
format = ' $symbol [${ram}]($style) '
style = 'bright-purple'

[[battery.display]]
threshold = 20
style = 'bold red'

[[battery.display]]
threshold = 40
style = 'bold orange'

[[battery.display]]
threshold = 60
style = 'yellow'

[[battery.display]]
threshold = 100
style = 'green'
